on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      coder_version:
        description: 'Coder Version'     
        required: true
        default: 'x.x.x'
      extra_version:
        description: 'Extra version (to amend AMI)'
        default: ''
        required: false

jobs:
  packer_release:
    runs-on: ubuntu-latest
    name: packer
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=release_char::$(printf ${{ github.event.release.name }} | tail -c 1)"

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: template.pkr.hcl

      - name: Install plugins
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: template.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: template.pkr.hcl
        env:
          PKR_VAR_coder_version: ${{ github.event.inputs.coder_version }}
          PKR_VAR_extra_version: ${{ github.event.inputs.extra_version }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
